bookroom/urls.py
from django.urls import path 
from .import views 


app_name = "bookroom"
urlpatterns =[
    path("",views.home, name ="home"),
    path("AvailableRoom/", views.AvailableRoom, name = "AvailableRoom"),
    
    path("booking/<int:booking_id>/", views.booking, name= "booking"),
    path("viewRoom/<int:view_id>/", views.viewRoom, name = "viewRoom"),
   
    
    path("checkout/", views.checkout, name = "checkout"),
    path("searchdate/", views.searchdate, name = "searchdate"),
]

hotelbooking/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("bookroom.urls")),
]

urlpatterns  += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

bookroom/models.py
from django.db import models
# Create your models here.
#below is for the admin only
class Rooms(models.Model):
    start_date = models.DateField(blank=True , null=True)  # a date on which the room is booked for
    end_date = models.DateField(blank=True ,  null=True)
    name = models.CharField(max_length=100)
    roomType = models.CharField(max_length= 80)  # single, double or dom ...Maybe I shoud make this to be choice model
    priceRate = models.IntegerField()
    roomDescription = models.CharField(max_length=200)
    room_available = models.BooleanField(default = True)
    thumbanil = models.ImageField(null = False)
    def __str__(self):
        return self.roomType

class BookerDetails(models.Model):
    rooms = models.ForeignKey(Rooms, on_delete=models.CASCADE)
    fullName = models.CharField(max_length=100)  
    valid_Id = models.IntegerField()
    email = models.EmailField()
    phone_number = models.IntegerField()
    def __str__(self):
        return self.fullName
    
class RoomPictures(models.Model):
    room = models.ForeignKey(Rooms,on_delete =models.CASCADE)
    picture = models.ImageField(null = True)
    def __str__(self):
        return f'picture for  " {self.room.name} " '
    
class Extras(models.Model):
    rooms = models.ForeignKey(Rooms, on_delete=models.CASCADE)
    breakfast = models.BooleanField()
    wifi = models.BooleanField()
    cleaning = models.BooleanField() 
    

    

bookroom/forms.py
from django.forms import DateInput, ModelForm
from . models import BookerDetails , Extras , Rooms
from django import forms

from bootstrap_datepicker_plus.widgets import DatePickerInput
# my forms will go here

class BookerInfo(ModelForm):
    
    class Meta :
        model = BookerDetails
        fields = ['fullName','valid_Id','phone_number','email']

        
        
class AddExtras(ModelForm):
    class Meta :
        model = Extras
        fields = ['breakfast', 'wifi', 'cleaning']

bookroom/views.py
from django.shortcuts import render, redirect
from .models import BookerDetails , Extras , Rooms
from .forms import BookerInfo , AddExtras
import datetime

# Create your views here. 

def home(request):
    import time
    search = request.POST.get('userdate1')
    search2 = request.POST.get('userdate2')
    
    
    
    if search:
        #  my model has start_date and end_date
        
        
        search1C = search.replace("/","-")  
        search2C = search2.replace("/","-")
        rooms = Rooms.objects.all() #all my rooms
        avail_rooms = []
        
        request.session["search1C"] = search1C
        request.session["search2C"] = search2C
        
        for i in rooms:
            if i.start_date > datetime.datetime.strptime(search1C, "%Y-%m-%d").date() and  i.start_date > datetime.datetime.strptime(search2C, "%Y-%m-%d").date():
                avail_rooms.append(i)
                
        for x in rooms:
            if i.end_date < datetime.datetime.strptime(search1C, "%Y-%m-%d").date() and i.end_date < datetime.datetime.strptime(search2C, "%Y-%m-%d").date():
                avail_rooms.append(x)        
      
        context = {"avail":avail_rooms}
        return render (request , "bookroom/home.html" , context )     
        
    else:
        context = {}
        return render (request , "bookroom/home.html" , context )   
    

def booking(request, booking_id):
    rooms = Rooms.objects.get(id = booking_id)
    
    start_date = rooms.start_date
    end_date = rooms.end_date
    
    search1C = request.session['search1C'] # start date
    search2C = request.session['search2C']  # end date
    
    if request.method != 'POST':
        form = BookerInfo()
    else:
        form = BookerInfo(data=request.POST)
        if form.is_valid():
            myform = form.save(commit=False)
            myform.rooms = rooms
            rooms.room_available = False 
            
            rooms.start_date = search1C
            rooms.end_date = search2C
            
            
            myform.start_date = start_date
            myform.end_date = end_date
            
            
            myform.save()
            rooms.save(update_fields = ['room_available',"start_date","end_date"])
            return redirect('bookroom:home' )       
    
    context = {'rooms':rooms, "form":form,"start":search1C,"end":search2C}
    return render (request , "bookroom/booking.html" , context)

def viewRoom(request, view_id):
    view =  Rooms.objects.get(id = view_id)
    allrooms = Rooms.objects.exclude(id=view_id)
    context = {"view":view,"allrooms":allrooms}
    return render (request , "bookroom/viewRoom.html" , context)   

def AvailableRoom(request):
    rooms = Rooms.objects.all()
    context = {'rooms':rooms}
    return render (request, "bookroom/available.html" , context) 



def checkout(request):
    search = request.GET['userdate1']
    search2 = request.GET['userdate2']
    
    search1C = search.replace("/","-")  # finale converted date and time ...
    search2C = search2.replace("/","-")

    rooms = Rooms.objects.filter(start_date__range = [search1C,search2C])
    #rooms = Rooms.objects.all()
    context = {"rooms":rooms}
  
    return render (request , "bookroom/checkout.html" , context  )

def searchdate(request): 
    search = request.POST.get('userdate1')
    search2 = request.POST.get('userdate2')
    
    
    if search:
        #  my model has start_date and end_date
        search1C = search.replace("/","-")  
        search2C = search2.replace("/","-")
        rooms = Rooms.objects.all() #all my rooms
        avail_rooms = []
        
        for i in rooms:
            if i.start_date > datetime.datetime.strptime(search1C, "%Y-%m-%d").date() and  i.start_date > datetime.datetime.strptime(search2C, "%Y-%m-%d").date():
                avail_rooms.append(i)
                
        for x in rooms:
            if i.end_date < datetime.datetime.strptime(search1C, "%Y-%m-%d").date() and i.end_date < datetime.datetime.strptime(search2C, "%Y-%m-%d").date():
                avail_rooms.append(x)        
      
        context = {"avail":avail_rooms}
        return render (request , "bookroom/check.html" , context )     
        
    else:
        context = {}
        return render (request , "bookroom/check.html" , context )   
    
    
"""
rooms = Rooms.objects.exclude(start_date__gte=search1C)
rooms = Rooms.objects.exclude(start_date__lte=search2C)

 booked_rooms = Rooms.objects.filter(start_date__gte=search1C) and Rooms.objects.filter(end_date__lte = search2C) # object of all the booked rooms
        
        available_rooms =[] # will contain all the non booked rooms
        
        for available_room in rooms:
            if available_room not in booked_rooms:
                available_rooms.append(available_room)
                
        for i in booked_rooms:
            if search2C <= booked_rooms.end_date:
                alias.append(i)                
                                
        for x in rooms:
            if alias not in rooms:
                available_room.append(x)
                

"""  

bookroom/templates/bookroom/available.html
{% extends 'bookroom/main.html' %}
{% load static %}
{% block content %}
 <center><h2>Available Rooms</h2></center>


 <div class = "container">
        
    <div class = "row">
        {% for room in rooms %}
        {% if room.room_available is True %}
        <div class = "col-lg-3">
            <br>
            <div style="box-shadow: 0 0 10px #626cfb;" class="card card-body">
                <img src = "{% static 'images/hotel.jpg' %}">
                <hr>
                <div style=" position:relative; ">
                    {% if room.room_available is True %}
                        status: <div style="color: green ;">available</div>
                    {% else %}
                        status:<div style="color: red ;">unavailable</div> 
                    {% endif %}
                </div>
                <div>
                    price: R{{room.priceRate}} p/night
                </div>
                <a class ="btn btn-outline-primary btn-sm" href ="{% url 'bookroom:viewRoom' room.id %}">View Room _>></a>
                {% if room.room_available is True %}
                <a class ="btn btn-outline-success btn-sm" href ="{% url 'bookroom:booking' room.id %}">Book Room + _>></a>
                {% endif%}
                <hr>
                <div style="color: rgb(12, 95, 248);">{{room.roomType}}</div>
            </div>
        </div>
          {% endif  %}
        {% endfor %}
    </div>

</div>



    {% endblock content%}

bookroom/templates/bookroom/booking.html
{% load static %}
{% load bootstrap5%}
{% bootstrap_css%}
{% bootstrap_javascript %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">

<header>
     <!-- header inner -->
     <div class="header" style="box-shadow: 0 0 3px ;position: relative;color: rgb(211, 211, 211);">
        <div class="container">
           <div class="row">
              <div class="col-xl-3 col-lg-3 col-md-3 col-sm-3 col logo_section">
                 <div class="full">
                    <div class="center-desk">
                       <div class="logo">
                          <a href="{% url 'bookroom:home' %}">
                             <h1 style="text-transform:none;font-size:xx-large;font-style: oblique;color: rgb(53, 53, 99);">
                                <strong>MyHotel_>></strong>  </h1>
                             </a>
                       </div>
                    </div>
                 </div>
              </div>
              <div class="col-xl-9 col-lg-9 col-md-9 col-sm-9">
                 <nav class="navigation navbar navbar-expand-md navbar-dark ">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample04" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarsExample04">
                       <ul class="navbar-nav mr-auto">
                         <li class="nav-item">
                           <a style="color: rgb(34, 34, 63);" class="nav-link" href="/">Home</a>
                        </li>
                          <li class="nav-item">
                             <a style="color: rgb(34, 34, 63);" class="nav-link" href="#">Gallery</a>
                          </li>
                          <li class="nav-item">
                             <a style="color: rgb(34, 34, 63);"  class="nav-link" href="#">Rooms</a>
                          </li>
                          <li class="nav-item">
                             <a style="color: rgb(34, 34, 63);"  class="nav-link" href="/#about">About</a>
                          </li>
                          <li class="nav-item">
                             <a style="color: rgb(34, 34, 63);" class="nav-link" href="/#contact">Contact us</a>
                          </li>
                       </ul>
                       
                    </div>
                 </nav>
              </div>
           </div>
        </div>
     </div>
   </header>

 <br>  
<div class="container"> 

<h2 style="font-weight:500">{{rooms.roomType}}</h2>
<div>
     <h4>From: <strong>{{start}}</strong></h4>
     
     <h4>To: <strong>{{end}}</strong></h4>
</div>


<center>   
<div class="col-sm-9" style="background-color: rgba(175, 175, 175, 0.5);padding: 1cm; margin: 1cm;border-radius: 15px 15px 15px 15px;">  
     
<form action="{% url 'bookroom:booking' rooms.id %}" method='post'>
    
     {% bootstrap_form form %}
     {{form.media}}
     {% csrf_token %}

     {% buttons %}
     <button class="btn btn-outline-success" name="submit">checkout_>></button>
     {% endbuttons %}
</form>
</div>
</center>
</div>

bookroom/templates/bookroom/check.html
{% extends 'bookroom/main.html' %}
{% load static %}
{% load bootstrap5%}
{% bootstrap_css%}
{% bootstrap_javascript %}

{% block content %}
<h1>chekout page</h1>

   




    <h4>available rooms</h4>

 







{% endblock content %}

bookroom/templates/bookroom/checkout.html
<ul>
  {% for room in rooms %}
  <ol>{{room.roomType}}</ol>
  {% endfor %}
  </ul>
  

bookroom/templates/bookroom/home1.html
{% extends 'bookroom/main.html' %}
{% load static %}
{% load bootstrap5%}
{% bootstrap_css%}
{% bootstrap_javascript %}

{% block content %}

<html>
  <head>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.10.1/umd/popper.min.js"
      integrity="sha512-8jeQKzUKh/0pqnK24AfqZYxlQ8JdQjl9gGONwGwKbJiEaAPkD3eoIjz3IuX4IrP+dnxkchGUeWdXLazLHin+UQ=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    ></script>

    <!-- Bootstrap is not required for the picker to work-->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
      integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
      crossorigin="anonymous"
    ></script>

    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <!-- end bootstrap-->

    <!-- Font awesome is not required provided you change the icon options -->
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/js/solid.min.js"
      integrity="sha512-C92U8X5fKxCN7C6A/AttDsqXQiB7gxwvg/9JCxcqR6KV+F0nvMBwL4wuQc+PwCfQGfazIe7Cm5g0VaHaoZ/BOQ=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    ></script>

    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/js/fontawesome.min.js"
      integrity="sha512-5qbIAL4qJ/FSsWfIq5Pd0qbqoZpk5NcUVeAAREV2Li4EKzyJDEGlADHhHOSSCw0tHP7z3Q4hNHJXa81P92borQ=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    ></script>
    <!-- end FA -->

    <script src="https://cdn.jsdelivr.net/gh/Eonasdan/tempus-dominus@master/dist/js/tempus-dominus.js"></script>

    <link
      href="
  https://cdn.jsdelivr.net/gh/Eonasdan/tempus-dominus@master/dist/css/tempus-dominus.css"
      rel="stylesheet"
    />
      
<!-- Popperjs -->
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.2/dist/umd/popper.min.js"
crossorigin="anonymous"></script>
<!-- Tempus Dominus JavaScript -->
<script src="https://cdn.jsdelivr.net/gh/Eonasdan/tempus-dominus@master/dist/js/tempus-dominus.js"
crossorigin="anonymous"></script>

<!-- Tempus Dominus Styles -->
<link href="https://cdn.jsdelivr.net/gh/Eonasdan/tempus-dominus@master/dist/css/tempus-dominus.css"
rel="stylesheet" crossorigin="anonymous">

 


<center>

    <form action="{% url 'bookroom:home' %}" method='POST'>
         {% csrf_token %}
               
    <div class='row'>
        <div class='col-sm-6'>
          <label for='linkedPickers1Input' class='form-label'>From</label>
          <div
            class='input-group log-event'
            id='linkedPickers1'
            data-td-target-input='nearest'
            data-td-target-toggle='nearest'
          >
            <input
              id='linkedPickers1Input'
			  name="userdate1"
              type='text'
              class='form-control'
              data-td-target='#linkedPickers1'
            />
            <span
              class='input-group-text'
              data-td-target='#linkedPickers1'
              data-td-toggle='datetimepicker'
            >
               <span class='fa-solid fa-calendar'></span>
             </span>
          </div>
        </div>
        <div class='col-sm-6'>
          <label for='linkedPickers2Input' class='form-label'>To</label>
          <div
            class='input-group log-event'
            id='linkedPickers2'
            data-td-target-input='nearest'
            data-td-target-toggle='nearest'
          >
            <input
          name="userdate2"
              id='linkedPickers2Input'
              type='text'
              class='form-control'
              data-td-target='#linkedPickers2'
            />
            <span
              class='input-group-text'
              data-td-target='#linkedPickers2'
              data-td-toggle='datetimepicker'
            >
               <span class='fa-solid fa-calendar'></span>
             </span>
          </div>
        </div>
    </div>
    <br>
    {% buttons %}
    <button class="btn btn-outline-success" name="submit">check availability</button>
    {% endbuttons %}
               
             
    </form>
    </center>

  


 <center><h2 style = "color: rgb(11, 72, 253);">All Rooms</h2></center>

           

 
    <div class = "container">
        
        <div class = "row">
            {% for room in avail %}
            <div class = "col-lg-3">
                <br>
                <div style="box-shadow: 0 0 10px #626cfb;" class="card card-body">
                    <img src = "{% static 'images/hotel.jpg' %}">
                    <hr>
                    <div style=" position:relative; ">
                        {% if room.room_available is True %}
                            status: <div style="color: green ;">available</div>
                        {% else %}
                            status:<div style="color: red ;">unavailable</div> 
                        {% endif %}
                    </div>
                    <div>
                        price: R{{room.priceRate}} p/night
                    </div>
                    <a class ="btn btn-outline-primary btn-sm" href ="{% url 'bookroom:viewRoom' room.id %}">View Room _>></a>
                    {% if room.room_available is True %}
                    <a class ="btn btn-outline-success btn-sm" href ="{% url 'bookroom:booking' room.id %}">Book Room + _>></a>
                    {% endif%}
                    <hr>
                    <div style="color: rgb(12, 95, 248);">{{room.roomType}}</div>
                </div>
            </div>
            {% endfor %}
        </div>

    </div>



    <script src="{% static 'date.js'%}"></script>
   





{% endblock content %}

bookroom/templates/bookroom/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Booking</title>
    
    {% load bootstrap5 %}
    {% bootstrap_css%}
    {% bootstrap_javascript%}
    {{form.media}}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel ="stylesheet" type="text/css" href ="{% static 'mycss.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
 


          <div style="width: 100%;">
            {% block content %}
        
            {% endblock content %}  
        </div>  
      </div>
  </div>
</div>

      
<!-- Popperjs -->
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.2/dist/umd/popper.min.js"
crossorigin="anonymous"></script>
<!-- Tempus Dominus JavaScript -->
<script src="https://cdn.jsdelivr.net/gh/Eonasdan/tempus-dominus@master/dist/js/tempus-dominus.js"
crossorigin="anonymous"></script>

<!-- Tempus Dominus Styles -->
<link href="https://cdn.jsdelivr.net/gh/Eonasdan/tempus-dominus@master/dist/css/tempus-dominus.css"
rel="stylesheet" crossorigin="anonymous">




</body>
</html>

bookroom/templates/bookroom/viewRoom.html
{% load static %}
{% load bootstrap5%}
{% bootstrap_css%}
{% bootstrap_javascript %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<header>
  <!-- header inner -->
  <div class="header" style="box-shadow: 0 0 3px ;position: relative;color: rgba(180, 179, 179, 0.856);">
     <div class="container">
        <div class="row">
           <div class="col-xl-3 col-lg-3 col-md-3 col-sm-3 col logo_section">
              <div class="full">
                 <div class="center-desk">
                    <div class="logo">
                       <a href="{% url 'bookroom:home' %}">
                          <h1 style="text-transform:none;font-size:xx-large;font-style: oblique;color: rgb(53, 53, 99);">
                             <strong>MyHotel_>></strong>  </h1>
                          </a>
                    </div>
                 </div>
              </div>
           </div>
           <div class="col-xl-9 col-lg-9 col-md-9 col-sm-9">
              <nav class="navigation navbar navbar-expand-md navbar-dark ">
                 <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample04" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
                 <span class="navbar-toggler-icon"></span>
                 </button>
                 <div class="collapse navbar-collapse" id="navbarsExample04">
                    <ul class="navbar-nav mr-auto">
                      <li class="nav-item">
                        <a style="color: rgb(34, 34, 63);" class="nav-link" href="/">Home</a>
                     </li>
                       <li class="nav-item">
                          <a style="color: rgb(34, 34, 63);" class="nav-link" href="#">Gallery</a>
                       </li>
                       <li class="nav-item">
                          <a style="color: rgb(34, 34, 63);"  class="nav-link" href="#">Rooms</a>
                       </li>
                       <li class="nav-item">
                          <a style="color: rgb(34, 34, 63);"  class="nav-link" href="/#about">About</a>
                       </li>
                       <li class="nav-item">
                          <a style="color: rgb(34, 34, 63);" class="nav-link" href="/#contact">Contact us</a>
                       </li>
                    </ul>
                    
                 </div>
              </nav>
           </div>
        </div>
     </div>
  </div>
</header>

<div class="container">

  <div class="row">
    <h2 style="margin-top: 0.5cm;margin-bottom: 0.2cm;">{{view.name}}</h3>
  </div>
 
  <div class="row">
    <div class="col col-md-9">
      <div style="min-height: 10cm;overflow-y: scroll;" class="card card-body">
        
        <div class="row">  
          {% for pic in view.roompictures_set.all %}
          <div class="col col-sm-4">  
            <div style="height: 170px;overflow: hidden;margin-bottom: 0.6cm;"> 
             <img class="img-thumbnail" src="{{pic.picture.url}}">  
            </div>
          </div>
          {% empty %}
          <center> <h5><strong>No Pictures Yet </strong></h5> </center>  
          {% endfor %} 
        </div>
        
      </div>
      <br>
      <div class="row">
        <div class="card card-body">
          <div><h3 style="font-weight:500;font-family: sans-serif;">  price: R {{view.priceRate}} /night</h3></div>
          <div style="width: 75%;color:rgb(73, 73, 73)">{{view.roomDescription}}</div>
        </div>
       
      </div>
    </div>

    <div class="col col=sm-3">
      
      <div class="card card-body">
        <h4><strong> More Rooms </strong></h4> 
        <div class="row">
          {% for room in allrooms %}
          <div class="col-sm-12">
              <a href="{%url 'bookroom:viewRoom' room.id %}"> {{room.name}} </a>
          </div>
          {% endfor %}
        </div>
      </div>
    
    </div>
  

  </div>

 


  
</div>